import { FaRegMoneyBillAlt } from 'react-icons/fa'

export { Navbar } from './Navbar'
export { Inicio } from '../pages/Inicio'
export { Instalaciones } from '../pages/Instalaciones'
export { Matricula } from '../pages/Matricula'
export { Nosotros } from '../pages/Nosotros'
export { Servicios } from '../pages/Servicios'
export { Footer } from './Footer'
export { Aulas } from './Aulas'
export { Jugamos } from './Jugamos'
export { Cuna } from '../pages/Cuna'
export { Jardin } from '../pages/Jardin'
export { Guarderia } from '../pages/Guarderia'
export { Estimulacion_psicopedagogica } from '../pages/Estimulacion_psicopedagogica'
export { EstimulacionTemprana} from '../pages/EstimulacionTemprana'
export { Escuela_de_padres } from '../pages/Escuela_de_padres'
export { Cocina } from '../pages/Cocina'
export { Destacamos } from './Destacamos'
export { NuestrosServicios } from './NuestrosServicios'